#!/usr/bin/env python3

import subprocess

from lines import checkfile
import changedfiles

def stashIndex():
    cmd = "git stash --keep-index --quiet".split()
    subprocess.call(cmd)

def stashPop():
    cmd = "git stash pop --quiet".split()
    subprocess.call(cmd)

def cleanup(exitcode):
    stashPop()
    exit(exitcode)

stashIndex()
linesOK = True
for filename in changedfiles.get_allExceptDeletions():
    if not checkfile(filename):
       linesOK = False

if not linesOK:

    cleanup(1)

cleanup(0)
