#!/usr/bin/env python3

import subprocess

from lines import checkfile
import changedfiles


def stashIndex():
    cmd = "git stash --keep-index --quiet".split()
    subprocess.call(cmd)


def stashPop():
    cmd = "git stash pop --quiet".split()
    subprocess.call(cmd)


def cleanup(exitcode):
    stashPop()
    exit(exitcode)


def checkformatting():
    """Check formatting staged files"""
    print("Check formatting...")
    linesOK = True
    for filename in changedfiles.get_allExceptDeletions():
        try:
            if not checkfile(filename):
                linesOK = False
        except e:
            print(e)
            cleanup(1)

    if not linesOK:
        print("*** Found formatting mistakes")
        cleanup(1)
    print("... formatting OK")


# stash non-staged changes away
stashIndex()
# check the formatting staged files
checkformatting()
# recover changes from stash
cleanup(0)
